"use client";
import React, { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SubHero } from "@/components/ui/SubHero";
import { SectionWrapper } from "@/components/ui/SectionWrapper";
import { GlassCard } from "@/components/ui/GlassCard";
import { HelpCircle, Cpu, Zap, ShieldCheck, ChevronDown, Terminal, Search, Info } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";

const CATEGORIES = [
  { id: "CYCLE", label: "PHASE_01::CYCLE_LOGIC" },
  { id: "THERMO", label: "PHASE_02::THERMODYNAMICS" },
  { id: "IMPL", label: "PHASE_03::IMPLEMENTATION" }
];

const FAQ_DATA = [
  {
    category: "CYCLE",
    icon: HelpCircle,
    question: "What is the HOPE engine cycle?",
    answer: "The HOPE (High-efficiency, Optimized-pressure Expansion) cycle is a patented thermodynamic process that integrates water injection for nearly isothermal compression and steam-assisted expansion. It represents a departure from traditional Otto/Diesel cycles by actively managing temperature gradients during the compression stroke."
  },
  {
    category: "THERMO",
    icon: Zap,
    question: "How is isothermal compression achieved?",
    answer: "By injecting finely atomized water during the compression stroke, the latent heat of vaporization absorbs the thermal energy generated by work. This keeps the air-water mixture near a constant temperature, minimizing the work required for compression and anchoring the cycle to a more efficient entropy path."
  },
  {
    category: "IMPL",
    icon: Cpu,
    question: "Is it compatible with current engine blocks?",
    answer: "The HOPE cycle requires specialized cylinder head modifications for water injection and specific timing controls. However, the core mechanical architecture—pistons, crankshafts, and connecting rods—remains compatible with established high-volume internal combustion manufacturing processes."
  },
  {
    category: "IMPL",
    icon: ShieldCheck,
    question: "How does it prevent engine knock?",
    answer: "Engine knock is primarily caused by auto-ignition due to excessive heat during compression. By maintaining near-isothermal conditions, the HOPE cycle strictly caps the end-of-compression temperature, effectively eliminating the knock limit and allowing for significantly higher overall pressure ratios."
  },
  {
    category: "THERMO",
    icon: Info,
    question: "What is the primary efficiency limit?",
    answer: "While the HOPE cycle pushes toward Carnot efficiency, real-world limits are dictated by the speed of heat transfer between the air and injected water. Our research focuses on maximizing surface area through advanced atomization to approach the theoretical limit in practical RPM ranges."
  }
];

const AccordionItem = ({ item, isOpen, onClick }: { item: any, isOpen: boolean, onClick: () => void }) => {
  return (
    <GlassCard className={cn(
      "overflow-hidden border-white/5 bg-[#030712]/50 backdrop-blur-xl transition-all duration-500",
      isOpen ? "ring-1 ring-blue-500/20 bg-[#030712]/80" : "hover:bg-white/[0.02]"
    )}>
      <button 
        onClick={onClick}
        className="w-full p-6 md:p-8 flex items-start gap-6 text-left group"
      >
        <div className={cn(
          "w-12 h-12 rounded-xl flex items-center justify-center shrink-0 transition-colors",
          isOpen ? "bg-blue-500/20 text-blue-400" : "bg-white/5 text-slate-500 group-hover:text-blue-400"
        )}>
          <item.icon className="w-5 h-5" />
        </div>
        <div className="flex-1 pt-3">
          <div className="flex items-center justify-between gap-4">
             <div className="flex flex-col">
                <h3 className="text-lg font-bold text-white tracking-tight">{item.question}</h3>
                <div className="flex items-center gap-2 mt-1 opacity-40">
                   <div className="w-1 h-1 rounded-full bg-blue-500" />
                   <span className="text-[8px] font-mono uppercase tracking-[0.2em]">REF_LOG::PHASE_DATA</span>
                </div>
             </div>
             <ChevronDown className={cn("w-5 h-5 text-slate-600 transition-transform duration-500", isOpen && "rotate-180 text-blue-400")} />
          </div>
          <AnimatePresence>
            {isOpen && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: "auto", opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                className="relative overflow-hidden"
              >
                {/* Technical Watermark */}
                <div className="absolute -right-8 -bottom-8 opacity-[0.03] rotate-12 pointer-events-none">
                   <Cpu className="w-48 h-48 text-white" />
                </div>
                
                <div className="pt-6 relative z-10">
                   <p className="text-slate-400 leading-relaxed font-light italic opacity-80 text-sm border-l border-blue-500/20 pl-6 py-2 bg-gradient-to-r from-blue-500/[0.02] to-transparent rounded-r-lg">
                     {item.answer}
                   </p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </button>
    </GlassCard>
  );
};

export default function FAQClient() {
  const [activeCategory, setActiveCategory] = useState("CYCLE");
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const filteredItems = FAQ_DATA.filter(item => item.category === activeCategory);

  return (
    <main className="min-h-screen bg-[#020617] text-white flex flex-col font-sans selection:bg-blue-500/30">
      <Header />
      
      <SubHero 
        badge="Technical Repository"
        title="Technical FAQ &"
        gradientTitle="Briefings"
        description="Detailed insights into the thermodynamics, mechanics, and implementation architecture of the HOPE cycle."
      />

      <SectionWrapper className="pt-0 pb-32">
        <div className="container px-6">
          <div className="max-w-4xl mx-auto space-y-16">
            
            {/* Knowledge Base Header */}
            <div className="flex flex-col md:flex-row items-center justify-between gap-8 border-b border-white/5 pb-10">
               <div className="flex items-center gap-4 group cursor-default">
                  <div className="relative">
                    <Terminal className="w-5 h-5 text-blue-500 relative z-10" />
                    <div className="absolute inset-0 bg-blue-500/20 blur-md animate-pulse" />
                  </div>
                  <div className="flex flex-col">
                     <span className="text-[10px] font-black tracking-[0.3em] text-blue-400 uppercase flex items-center gap-2">
                       KNOWLEDGE_BASE::v4.2
                       <span className="inline-block w-1 h-3 bg-blue-500 animate-blink" />
                     </span>
                     <span className="text-[8px] font-mono text-slate-600 uppercase">ACCESS_LEVEL::OPEN_RESOURCE</span>
                  </div>
               </div>
               <div className="flex gap-2 p-1 rounded-xl bg-white/[0.02] border border-white/5 backdrop-blur-md">
                 {CATEGORIES.map((cat) => (
                    <button
                      key={cat.id}
                      onClick={() => {
                        setActiveCategory(cat.id);
                        setOpenIndex(0);
                      }}
                      className={cn(
                        "px-4 py-2 rounded-lg text-[9px] font-black uppercase tracking-widest transition-all",
                        activeCategory === cat.id 
                          ? "bg-blue-600/90 text-white shadow-lg shadow-blue-500/20" 
                          : "text-slate-500 hover:text-white"
                      )}
                    >
                      {cat.id}
                    </button>
                 ))}
               </div>
            </div>

            {/* Accordion List */}
            <div className="space-y-4">
              <AnimatePresence mode="wait">
                <motion.div
                  key={activeCategory}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  transition={{ duration: 0.5 }}
                  className="space-y-4"
                >
                  {filteredItems.map((item, i) => (
                    <AccordionItem 
                      key={i} 
                      item={item} 
                      isOpen={openIndex === i} 
                      onClick={() => setOpenIndex(openIndex === i ? null : i)} 
                    />
                  ))}
                </motion.div>
              </AnimatePresence>
            </div>

            {/* Support Callout */}
            <div className="pt-16 text-center">
               <p className="text-slate-500 text-xs font-light italic mb-6">Can't find the technical specification you're looking for?</p>
               <button className="inline-flex items-center gap-2 group text-blue-400 hover:text-blue-300 transition-colors">
                  <span className="text-[10px] font-black uppercase tracking-[0.3em]">Request Technical Briefing</span>
                  <ChevronDown className="w-4 h-4 -rotate-90 group-hover:translate-x-1 transition-transform" />
               </button>
            </div>

          </div>
        </div>
      </SectionWrapper>

      <Footer />
    </main>
  );
}
