import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    items: [
      {
        metric_key: "vmax_cc",
        panel_key: "Input",
        panel_order: 1,
        item_order: 1,
        label: "Displacement (cc)",
        ui_role: "input",
        dtype: "number",
        default: 1000,
        min: 100,
        max: 5000,
      },
      {
        metric_key: "cr",
        panel_key: "Input",
        panel_order: 1,
        item_order: 2,
        label: "Compression Ratio",
        ui_role: "input",
        dtype: "number",
        default: 40,
        min: 2,
        max: 100,
      },
      {
        metric_key: "tcap",
        panel_key: "Input",
        panel_order: 1,
        item_order: 3,
        label: "Peak Temperature (K)",
        ui_role: "input",
        dtype: "number",
        default: 2500,
        min: 500,
        max: 5000,
      },
      {
        metric_key: "gamma_eff",
        panel_key: "Input",
        panel_order: 1,
        item_order: 4,
        label: "Gamma Effective (γ)",
        ui_role: "input",
        dtype: "number",
        default: 1.33,
        min: 1.1,
        max: 1.6,
      },
      {
        metric_key: "lambda",
        panel_key: "Input",
        panel_order: 1,
        item_order: 5,
        label: "Exhaust Lambda",
        ui_role: "input",
        dtype: "number",
        default: 1.0,
      },
      {
        metric_key: "rpm",
        panel_key: "Input",
        panel_order: 1,
        item_order: 6,
        label: "Engine RPM",
        ui_role: "input",
        dtype: "number",
        default: 3000,
      },
      {
        metric_key: "bore_stroke_ratio",
        panel_key: "Input",
        panel_order: 1,
        item_order: 7,
        label: "Bore/Stroke Ratio",
        ui_role: "input",
        dtype: "number",
        default: 1.0,
      },
      {
        metric_key: "P2_bar",
        panel_key: "Cycle States",
        panel_order: 2,
        item_order: 1,
        label: "P2 (Compression Pressure)",
        ui_role: "readonly",
        dtype: "number",
        format: "1dp",
      },
      {
        metric_key: "T2_C",
        panel_key: "Cycle States",
        panel_order: 2,
        item_order: 2,
        label: "T2 (Compression Temp °C)",
        ui_role: "readonly",
        dtype: "number",
        format: "1dp",
      },
      {
        metric_key: "P3_real_bar",
        panel_key: "Cycle States",
        panel_order: 2,
        item_order: 3,
        label: "P3 (Peak Pressure)",
        ui_role: "readonly",
        dtype: "number",
        format: "1dp",
      },
      {
        metric_key: "T3_real_C",
        panel_key: "Cycle States",
        panel_order: 2,
        item_order: 4,
        label: "T3 (Peak Temp °C)",
        ui_role: "readonly",
        dtype: "number",
        format: "1dp",
      },
      {
        metric_key: "P4_bar",
        panel_key: "Cycle States",
        panel_order: 2,
        item_order: 5,
        label: "P4 (Exhaust Pressure)",
        ui_role: "readonly",
        dtype: "number",
        format: "1dp",
      },
      {
        metric_key: "T4_C",
        panel_key: "Cycle States",
        panel_order: 2,
        item_order: 6,
        label: "T4 (Exhaust Temp °C)",
        ui_role: "readonly",
        dtype: "number",
        format: "1dp",
      },
      {
        metric_key: "Q_in_J",
        panel_key: "Energy & Work",
        panel_order: 3,
        item_order: 1,
        label: "Heat Input (Q_in)",
        ui_role: "readonly",
        dtype: "number",
        format: "int",
      },
      {
        metric_key: "W_comp_J",
        panel_key: "Energy & Work",
        panel_order: 3,
        item_order: 2,
        label: "Compression Work",
        ui_role: "readonly",
        dtype: "number",
        format: "int",
      },
      {
        metric_key: "W_exp_real_J",
        panel_key: "Energy & Work",
        panel_order: 3,
        item_order: 3,
        label: "Expansion Work",
        ui_role: "readonly",
        dtype: "number",
        format: "int",
      },
      {
        metric_key: "W_brake_J",
        panel_key: "Energy & Work",
        panel_order: 3,
        item_order: 4,
        label: "Net Brake Work",
        ui_role: "readonly",
        dtype: "number",
        format: "int",
      },
      {
        metric_key: "IMEP_bar",
        panel_key: "Performance",
        panel_order: 4,
        item_order: 1,
        label: "IMEP Output",
        ui_role: "readonly",
        dtype: "number",
        format: "2dp",
      },
      {
        metric_key: "eta_brake_pct",
        panel_key: "Performance",
        panel_order: 4,
        item_order: 2,
        label: "Brake Efficiency",
        ui_role: "readonly",
        dtype: "percent",
        format: "percent_1",
      },
      {
        metric_key: "bsfc_g_kWh",
        panel_key: "Performance",
        panel_order: 4,
        item_order: 3,
        label: "BSFC",
        ui_role: "readonly",
        dtype: "number",
        format: "1dp",
      },
      {
        metric_key: "T_avg_K",
        panel_key: "Advanced",
        panel_order: 5,
        item_order: 1,
        label: "Cycle Avg Temp (K)",
        ui_role: "readonly",
        dtype: "number",
        format: "int",
      },
      {
        metric_key: "Water_Dose_g",
        panel_key: "Advanced",
        panel_order: 5,
        item_order: 2,
        label: "Water Dose Proxy",
        ui_role: "readonly",
        dtype: "number",
        format: "2dp",
      },
    ],
  });
}
